name: cognito-local
services:
  cognito:
    build: .
    container_name: cognito-local
    restart: always
    ports:
      - "9229:9229"
    expose:
      - "9229"
    environment:
      - CONFIG_FILE=/config/config.json
      - USERS_FILE=/config/users.json
      - DATA_DIR=/temp-data
    volumes:
      - "./config/config.example.json:/config/config.json"
      - "./config/users.example.json:/config/users.json"
      - "./temp-data:/temp-data"
